basePath = "./source/"
rPath = basePath + "Randomizer/"
rcPath = basePath + "RandomizerCollection/"

require basePath + "Hash.rb"
require rPath + "Randomizer.rb"
require rPath + "Coin.rb"
require rPath + "Die.rb"
require rcPath + "RandomizerCollection.rb"
require rcPath + "Hand.rb"
require rcPath + "Cup.rb"
require rcPath + "Bag.rb"
require basePath + "Results.rb"
require basePath + "Player.rb"
